### PR TITLE
Removed horizontal scroll on the website

### PR DESCRIPTION
**Pull request by prakhar1989**
Hi!

Thanks for this great project. I've taken up distributed systems at school and the website has proven to be of immense use! Thank you. :beers: 

This quick fix basically gets rid of the annoying horizontal scroll that shows up even on wide screens. I'm assuming the horizontal scroll is a bug and not intentional. In case I'm wrong please feel free to close this issue :grinning: 

screen shot 2015-09-17 at 8 44 54 pm

### CODE REVIEW

**Comment by denizalti** [comment]
Hi!

Thanks for the merge request, it's merged now! I'm glad you found the work useful. Let me know if you have any other suggestions!

Thanks again,
Deniz..

**Comment by prakhar1989** [comment]
Thanks Deniz. I have a small question - in the [glossary](http://paxos.systems/glossary.html#consensus) page, the section under consensus states that

>  Paxos solves the consensus problem in an asynchronous environment, where processes can crash.

Whereas the FLP section states -

>  FLP Impossibility Result: Consensus problem is not solvable in an asynchronous system.

Aren't these two statements at odd with each other?

**Comment by denizalti** [comment]
Yes, great question! The FLP result says that there exists a circumstance, where any protocol trying to reach consensus in an asynchronous environment where processes can crash (such as Paxos) might stay forever indecisive, not being able to reach consensus. This is also true for Paxos (and I'll add this case to the consensus definition under glossary). We talk about this in detail under [When Paxos Works](http://paxos.systems/when.html).

I hope this helps!

**Comment by prakhar1989** [comment]
Ah okay. Thanks a lot for the clarification. I believe adding this caveat in the glossary itself might be quite helpful. :smile:

**Comment by denizalti** [comment]
I just did! :) Thanks!

**Comment by prakhar1989** [comment]
Wow that was quick! Thank you! Do you mind if I keep posting subsequent queries on this thread? You can get to them as and when you are free - no pressure. 

In return, I'll be more than happy to contribute in any way I can to this / other projects of yours :grinning: Please feel free to let me know if I can be of use.

Thank you!

**Comment by denizalti** [comment]
Sure, feel free to let me know of your corrections/suggestions!

Thanks!

**Pull request merged**
